apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: chain-mail
build:
  artifacts:
  - image: chain-mail
    context: code
    sync:
      manual:
      - src: 'code/*'
        dest: /project/*
deploy:
  kubectl:
    manifests:
      - ./k8s/*
