apiVersion: v1
kind: Service
metadata:
  name: maildev-service
spec:
  type: NodePort
  selector:
    app: maildev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
      name: web-port
    - protocol: TCP
      port: 25
      targetPort: 25
      nodePort: 30025
      name: mail-port
