apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-server-service
spec:
  type: NodePort
  selector:
    app: rabbitmq-server
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30072
      name: message-port
    - protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30672
      name: web-port

